# ─────────────────────────────────────────────────────────────────────────────
# 文件：_quarto.yml
# ─────────────────────────────────────────────────────────────────────────────

# —— 顶层元数据 ——
title: "在R中使用 Python 模块 Mesa 来创建 ABM 模型"
author:
  - "楼上"
  - "Mesa 开发团队 (提供demo)"

project:
  type: website
  output-dir: docs

website:
  title: "在R中使用 Python 模块 Mesa 来创建 ABM 模型"
  # 只要一个页面，就不需要额外的导航栏配置

format:
  html:
    theme:
      light: flatly
      dark: darkly
    respect-user-color-scheme: true

    # 目录配置
    toc: true
    toc-location: left
    toc-depth: 5

    # 页面布局：full 是“宽屏”模式的有效选项
    page-layout: full

    # 代码与图表配置
    fig-align: center
    highlight-style: github
    code-copy: true
    number-sections: true

    # 侧边栏宽度（即使没有多页，也会影响 toc 宽度）
    grid:
      sidebar-width: 300px

filters:
  - language-marker
